[tool.poetry]
name = "ldict"
version = "0.210317.0"
description = "Uniquely identified lazy dict"
authors = ["davips <dpsabc@gmail.com>"]
license = "GPL"
packages = [
    { include = "ldict", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.8"
orjson = "^3.5.0"
hosh = "^0.2103.0"

[tool.poetry.dev-dependencies]
autoreadme = "^0.2102.20"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
